language: php
php:
  - 5.6
  
services:
  - mongodb

before_install:
  - chmod +x rest/tests/travis/mongodb-install.sh
  
install:
  - rest/tests/travis/mongodb-install.sh

before_script:  
    - sudo apt-get install apache2
    - sudo a2enmod actions
    - sudo a2enmod rewrite
    - echo "export PATH=/home/vagrant/.phpenv/bin:$PATH" | sudo tee -a /etc/apache2/envvars > /dev/null
    - echo "$(curl -fsSL https://gist.github.com/roderik/16d751c979fdeb5a14e3/raw/gistfile1.txt)" | sudo tee /etc/apache2/conf.d/phpconfig > /dev/null
    - echo "$(curl -fsSL https://gist.github.com/roderik/2eb301570ed4a1f4c33d/raw/gistfile1.txt)" | sed -e "s,PATH,`pwd`/web,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
    - sudo service apache2 restart
    - cd rest && composer update

script:   
    - cd .. && phpunit --configuration phpunit.xml
