language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  
services:
  - mongodb

install:
  - rest/tests/travis/mongodb-install.sh

before_script:  
    - cd rest && composer update

script: phpunit rest/tests
